var FRAUD_STATUS = {
	ACCEPTED : 'ACCEPTED',
	REJECTED : 'REJECTED',
	PENDING : 'PENDING',
	ACCEPTED_AFTER_REVIEW : 'ACCEPTED_AFTER_REVIEW',
	REJECTED_AFTER_REVIEW : 'REJECTED_AFTER_REVIEW'
}

var PAYMENT_METHOD = 'KLARNA_CHECKOUT';

var ORDER_LINE_TYPE = 	{
	DISCOUNT : 'discount',
	SHIPPING_FEE : 'shipping_fee',
	SALES_TAX : 'sales_tax',
	PHYSICAL : 'physical',
	SURCHARGE : 'surcharge'
}

module.exports.FRAUD_STATUS = FRAUD_STATUS;
module.exports.PAYMENT_METHOD = PAYMENT_METHOD;
module.exports.ORDER_LINE_TYPE = ORDER_LINE_TYPE;