klarna.network.session.token.saved=Network session token saved successfully
klarna.network.session.token.missing=Network session token missing
klarna.network.session.token.disabled=Saving network session token is available only for Klarna payments integrated via PSP
